version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 32.2.0
    - 32.3.1
    - 32.3.2
  - dependency-name: "@types/node"
    versions:
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 15.0.0
  - dependency-name: "@angular/cli"
    versions:
    - 11.2.1
    - 11.2.10
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1102.10
    - 0.1102.3
    - 0.1102.4
    - 0.1102.5
    - 0.1102.7
    - 0.1102.8
    - 0.1102.9
  - dependency-name: tslib
    versions:
    - 2.2.0
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.21.0
    - 4.22.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: "@angular-eslint/template-parser"
    versions:
    - 2.1.0
  - dependency-name: jasmine-spec-reporter
    versions:
    - 7.0.0
  - dependency-name: "@angular-eslint/builder"
    versions:
    - 2.1.0
  - dependency-name: "@angular-eslint/eslint-plugin"
    versions:
    - 2.1.0
  - dependency-name: "@angular-eslint/eslint-plugin-template"
    versions:
    - 2.0.1
    - 2.1.0
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.6
    - 3.6.7
    - 3.6.8
    - 3.6.9
  - dependency-name: karma
    versions:
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
